In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
movies_df = pd.read_csv('movies.txt')

In [ ]:
movies_df.head(10)

,title,overview
0,The Shawshank Redemption,Two imprisoned men bond over a number of years...
1,The Godfather,The aging patriarch of an organized crime dyna...
2,The Godfather: Part II,The early life and career of Vito Corleone in...
3,The Dark Knight,When the menace known as the Joker wreaks havo...
4,12 Angry Men,A jury holdout attempts to prevent a miscarria...
5,Schindler's List,In German-occupied Poland during World War II ...
6,The Lord of the Rings: The Return of the King,Gandalf and Aragorn lead the World of Men agai...
7,Pulp Fiction,The lives of two mob hitmen a boxer a gangster...
8,The Lord of the Rings: The Fellowship of the Ring,A meek Hobbit from the Shire and eight compani...
9,Forrest Gump,The presidencies of Kennedy and Johnson the ev...

In [ ]:
movies_df.columns
movies_df.dropna(subset=['overview'], inplace=True)

In [ ]:
tfidf = TfidfVectorizer(stop_words='english')
movies_df['overview'] = movies_df['overview'].fillna('')
tfidf_matrix = tfidf.fit_transform(movies_df['overview'])

In [ ]:
print(tfidf_matrix)

  (0, 133)	0.2964019589174029
  (0, 91)	0.2964019589174029
  (0, 17)	0.2964019589174029
  (0, 423)	0.25850910094201784
  (0, 173)	0.2964019589174029
  (0, 480)	0.2964019589174029
  (0, 190)	0.2964019589174029
  (0, 570)	0.25850910094201784
  (0, 357)	0.2964019589174029
  (0, 59)	0.2964019589174029
  (0, 326)	0.2750618079807428
  (0, 257)	0.2964019589174029
  (1, 484)	0.2190751778452752
  (1, 425)	0.3135534304081692
  (1, 162)	0.3135534304081692
  (1, 83)	0.3135534304081692
  (1, 99)	0.3135534304081692
  (1, 528)	0.3135534304081692
  (1, 155)	0.3135534304081692
  (1, 116)	0.25916072805401213
  (1, 367)	0.3135534304081692
  (1, 379)	0.3135534304081692
  (1, 24)	0.3135534304081692
  (2, 184)	0.21666256206528178
  (2, 222)	0.26213574134748324
  :	:
  (57, 264)	0.2604363512885018
  (57, 398)	0.2604363512885018
  (57, 561)	0.2604363512885018
  (57, 245)	0.2604363512885018
  (57, 276)	0.2604363512885018
  (57, 229)	0.2604363512885018
  (57, 243)	0.2364433684310485
  (57, 377)	0.2364433684310485
  (57, 185)	0.21942007618048354
  (57, 474)	0.21942007618048354
  (57, 553)	0.21942007618048354
  (57, 184)	0.1954270933230303
  (57, 484)	0.16519950976756503
  (58, 21)	0.24274134812600973
  (58, 281)	0.24274134812600973
  (58, 512)	0.2252646181256492
  (58, 96)	0.48548269625201945
  (58, 445)	0.24274134812600973
  (58, 291)	0.24274134812600973
  (58, 182)	0.24274134812600973
  (58, 251)	0.24274134812600973
  (58, 124)	0.48548269625201945
  (58, 406)	0.21170861317753523
  (58, 395)	0.2252646181256492
  (58, 484)	0.1695998157056742

In [ ]:
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [ ]:
dataframe=pd.DataFrame(cosine_sim)
dataframe

,0,1,2,3,4,5,6,7,8,9,...,49,50,51,52,53,54,55,56,57,58
0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.063245,0.065284,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.047246,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,1.000000,0.040124,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.091540,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.036191,0.037155
2,0.000000,0.040124,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.950822,0.038343,0.000000,0.000000,0.000000,0.000000,0.000000,0.072598,0.031062
3,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.081771,0.035344,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.054232,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.857025,0.000000,0.053480,0.000000,0.000000
6,0.063245,0.000000,0.000000,0.000000,0.000000,0.054232,1.000000,0.000000,0.112077,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.054232,0.000000,0.000000,0.000000,0.000000
7,0.065284,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.048331,0.058961,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.112077,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.063457,0.000000,0.000000,0.051139,0.000000,0.050807
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,0.000000,0.000000,0.044809,0.000000,0.000000,0.000000,0.159309,0.000000,0.047036,0.000000,...,0.069287,0.042605,0.032870,0.029238,0.042300,0.000000,0.000000,0.000000,0.000000,0.000000
12,0.000000,0.000000,0.000000,0.000000,0.000000,0.054665,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.065207,0.054665,0.000000,0.000000,0.000000,0.000000
13,0.000000,0.045928,0.034896,0.000000,0.000000,0.000000,0.000000,0.136864,0.000000,0.000000,...,0.000000,0.115710,0.000000,0.000000,0.000000,0.000000,0.000000,0.035788,0.000000,0.000000
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.033563,...,0.036339,0.000000,0.000000,0.046392,0.000000,0.000000,0.052651,0.000000,0.052345,0.000000
16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.181965,0.000000,0.054546,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,0.000000,0.044023,0.036804,0.000000,0.000000,0.062954,0.000000,0.000000,0.000000,0.037551,...,0.088677,0.034994,0.000000,0.037420,0.054138,0.136055,0.000000,0.000000,0.033197,0.087187
18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.064610,0.093476,0.000000,0.000000,0.000000,0.000000,0.000000
19,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.055327,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.064157,0.000000,0.033591,...,0.000000,0.000000,0.000000,0.000000,0.053287,0.000000,0.000000,0.000000,0.000000,0.000000
23,0.000000,0.000000,0.032789,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.031177,0.030322,0.000000,0.055512,0.000000,0.000000,0.044737,0.029576,0.000000
24,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,0.000000,0.000000,0.051616,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.049077,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.046557,0.000000
26,0.000000,0.037155,0.031062,0.000000,0.000000,0.000000,0.000000,0.000000,0.050807,0.000000,...,0.000000,0.029535,0.000000,0.000000,0.063378,0.000000,0.000000,0.000000,0.028018,1.000000
27,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.044293,0.000000
28,0.044921,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.065989,0.109466,0.000000,0.000000,0.000000,0.000000,0.047109,0.000000
29,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.089632,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.053654,0.000000
30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.033007,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
32,0.000000,0.000000,0.071740,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.068212,0.000000,0.000000,0.045648,0.000000,0.000000,0.000000,0.000000,0.000000
33,0.000000,0.030362,0.025383,0.000000,0.000000,0.068883,0.049147,0.000000,0.000000,0.000000,...,0.028040,0.024134,0.000000,0.000000,0.000000,0.068883,0.000000,0.000000,0.022895,0.060130
34,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.029578,...,0.032025,0.000000,0.000000,0.000000,0.068684,0.000000,0.092800,0.000000,0.000000,0.000000
35,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.042544,...,0.046063,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
36,0.000000,0.000000,0.047032,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.044719,0.000000,0.000000,0.087612,0.000000,0.000000,0.000000,0.058843,0.000000
37,0.000000,0.000000,0.000000,0.000000,0.000000,0.059931,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
38,0.000000,0.000000,0.000000,0.000000,0.067744,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.050012,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
39,0.000000,0.000000,0.000000,0.037033,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.031432,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
40,0.000000,0.000000,0.000000,0.045607,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.038710,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
41,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.063245,0.065284,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.047246,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
42,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
43,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.081771,0.035344,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
44,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
45,0.065284,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.048331,0.058961,0.000000
46,0.000000,0.000000,0.000000,0.000000,0.000000,0.054665,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.065207,0.054665,0.000000,0.000000,0.000000,0.000000
47,0.000000,1.000000,0.040124,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.091540,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.036191,0.037155
48,0.000000,0.045928,0.034896,0.000000,0.000000,0.000000,0.000000,0.136864,0.000000,0.000000,...,0.000000,0.115710,0.000000,0.000000,0.000000,0.000000,0.000000,0.035788,0.000000,0.000000
49,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.064610,0.093476,0.000000,0.000000,0.000000,0.000000,0.000000
50,0.000000,0.091540,0.950822,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.036457,0.000000,0.000000,0.000000,0.000000,0.000000,0.069028,0.029535
51,0.000000,0.000000,0.038343,0.081771,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.036457,1.000000,0.034702,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
52,0.047246,0.000000,0.000000,0.035344,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.064610,0.000000,0.034702,1.000000,0.039445,0.000000,0.000000,0.000000,0.042670,0.000000
53,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.063457,0.000000,...,0.093476,0.000000,0.000000,0.039445,1.000000,0.000000,0.000000,0.063793,0.000000,0.063378
54,0.000000,0.000000,0.000000,0.000000,0.000000,0.857025,0.054232,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.053480,0.000000,0.000000
55,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
56,0.000000,0.000000,0.000000,0.000000,0.000000,0.053480,0.000000,0.048331,0.051139,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.063793,0.053480,0.000000,1.000000,0.000000,0.000000
57,0.000000,0.036191,0.072598,0.000000,0.000000,0.000000,0.000000,0.058961,0.000000,0.000000,...,0.000000,0.069028,0.000000,0.042670,0.000000,0.000000,0.000000,0.000000,1.000000,0.028018
58,0.000000,0.037155,0.031062,0.000000,0.000000,0.000000,0.000000,0.000000,0.050807,0.000000,...,0.000000,0.029535,0.000000,0.000000,0.063378,0.000000,0.000000,0.000000,0.028018,1.000000

In [ ]:
from scipy import sparse
def standardize(row):
    new_row = (row - row.mean())/(row.max()-row.min())
    return new_row

df_std = dataframe.apply(standardize)
print(df_std)

sparse_df = sparse.csr_matrix(df_std.values)
corrMatrix = pd.DataFrame(cosine_similarity(sparse_df),index=dataframe.columns,columns=dataframe.columns)
corrMatrix

          0         1         2         3         4         5         6   \
0   0.961255 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404  0.036881
1  -0.038745  0.959180 -0.003675 -0.037284 -0.018097 -0.038404 -0.026364
2  -0.038745 -0.000697  0.956202 -0.037284 -0.018097 -0.038404 -0.026364
3  -0.038745 -0.040820 -0.043798  0.962716 -0.018097 -0.038404 -0.026364
4  -0.038745 -0.040820 -0.043798 -0.037284  0.981903 -0.038404 -0.026364
5  -0.038745 -0.040820 -0.043798 -0.037284 -0.018097  0.961596  0.027868
6   0.024499 -0.040820 -0.043798 -0.037284 -0.018097  0.015828  0.973636
7   0.026539 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
8  -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404  0.085713
9  -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
10 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
11 -0.038745 -0.040820  0.001011 -0.037284 -0.018097 -0.038404  0.132945
12 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097  0.016261 -0.026364
13 -0.038745  0.005107 -0.008903 -0.037284 -0.018097 -0.038404 -0.026364
14 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
15 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
16 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
17 -0.038745  0.003203 -0.006994 -0.037284 -0.018097  0.024550 -0.026364
18 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
19 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
20 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
21 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
22 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
23 -0.038745 -0.040820 -0.011009 -0.037284 -0.018097 -0.038404 -0.026364
24 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
25 -0.038745 -0.040820  0.007817 -0.037284 -0.018097 -0.038404 -0.026364
26 -0.038745 -0.003665 -0.012736 -0.037284 -0.018097 -0.038404 -0.026364
27 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
28  0.006176 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
29 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
30 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
31 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
32 -0.038745 -0.040820  0.027941 -0.037284 -0.018097 -0.038404 -0.026364
33 -0.038745 -0.010459 -0.018415 -0.037284 -0.018097  0.030479  0.022783
34 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
35 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
36 -0.038745 -0.040820  0.003233 -0.037284 -0.018097 -0.038404 -0.026364
37 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097  0.021527 -0.026364
38 -0.038745 -0.040820 -0.043798 -0.037284  0.049647 -0.038404 -0.026364
39 -0.038745 -0.040820 -0.043798 -0.000251 -0.018097 -0.038404 -0.026364
40 -0.038745 -0.040820 -0.043798  0.008323 -0.018097 -0.038404 -0.026364
41  0.961255 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404  0.036881
42 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
43 -0.038745 -0.040820 -0.043798  0.962716 -0.018097 -0.038404 -0.026364
44 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
45  0.026539 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
46 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097  0.016261 -0.026364
47 -0.038745  0.959180 -0.003675 -0.037284 -0.018097 -0.038404 -0.026364
48 -0.038745  0.005107 -0.008903 -0.037284 -0.018097 -0.038404 -0.026364
49 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
50 -0.038745  0.050719  0.907023 -0.037284 -0.018097 -0.038404 -0.026364
51 -0.038745 -0.040820 -0.005456  0.044487 -0.018097 -0.038404 -0.026364
52  0.008501 -0.040820 -0.043798 -0.001940 -0.018097 -0.038404 -0.026364
53 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
54 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097  0.818621  0.027868
55 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097 -0.038404 -0.026364
56 -0.038745 -0.040820 -0.043798 -0.037284 -0.018097  0.015076 -0.026364
57 -0.038745 -0.004629  0.028800 -0.037284 -0.018097 -0.038404 -0.026364
58 -0.038745 -0.003665 -0.012736 -0.037284 -0.018097 -0.038404 -0.026364

          7         8         9   ...        49        50        51        52  \
0   0.021627 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691  0.017429
1  -0.043657 -0.023311 -0.038415  ... -0.046161  0.043662 -0.024691 -0.029817
2  -0.043657 -0.023311 -0.038415  ... -0.046161  0.902944  0.013652 -0.029817
3  -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878  0.057080  0.005527
4  -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
5  -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
6  -0.043657  0.088767 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
7   0.956343 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
8  -0.043657  0.976689 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
9  -0.043657 -0.023311  0.961585  ... -0.046161 -0.047878 -0.024691 -0.029817
10 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
11 -0.043657  0.023725 -0.038415  ...  0.023126 -0.005273  0.008179 -0.000579
12 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
13  0.093207 -0.023311 -0.038415  ... -0.046161  0.067833 -0.024691 -0.029817
14 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
15 -0.043657 -0.023311 -0.004851  ... -0.009822 -0.047878 -0.024691  0.016575
16 -0.043657 -0.023311 -0.038415  ...  0.135804 -0.047878  0.029854 -0.029817
17 -0.043657 -0.023311 -0.000863  ...  0.042516 -0.012884 -0.024691  0.007603
18 -0.043657 -0.023311 -0.038415  ...  0.953839 -0.047878 -0.024691  0.034793
19 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
20 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691  0.025510
21 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
22  0.020500 -0.023311 -0.004824  ... -0.046161 -0.047878 -0.024691 -0.029817
23 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.016701  0.005631 -0.029817
24 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
25 -0.043657 -0.023311 -0.038415  ... -0.046161  0.001199 -0.024691 -0.029817
26 -0.043657  0.027496 -0.038415  ... -0.046161 -0.018343 -0.024691 -0.029817
27 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
28 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878  0.041298  0.079649
29 -0.043657 -0.023311  0.051218  ... -0.046161 -0.047878 -0.024691 -0.029817
30 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
31 -0.043657 -0.023311 -0.038415  ... -0.013154 -0.047878 -0.024691 -0.029817
32 -0.043657 -0.023311 -0.038415  ... -0.046161  0.020334 -0.024691 -0.029817
33 -0.043657 -0.023311 -0.038415  ... -0.018121 -0.023743 -0.024691 -0.029817
34 -0.043657 -0.023311 -0.008836  ... -0.014136 -0.047878 -0.024691 -0.029817
35 -0.043657 -0.023311  0.004129  ... -0.000098 -0.047878 -0.024691 -0.029817
36 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.003159 -0.024691 -0.029817
37 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
38 -0.043657 -0.023311 -0.038415  ...  0.003851 -0.047878 -0.024691 -0.029817
39 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691  0.001615
40 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691  0.008893
41  0.021627 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691  0.017429
42 -0.043657 -0.023311  0.961585  ... -0.046161 -0.047878 -0.024691 -0.029817
43 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878  0.057080  0.005527
44 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
45  0.956343 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
46 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
47 -0.043657 -0.023311 -0.038415  ... -0.046161  0.043662 -0.024691 -0.029817
48  0.093207 -0.023311 -0.038415  ... -0.046161  0.067833 -0.024691 -0.029817
49 -0.043657 -0.023311 -0.038415  ...  0.953839 -0.047878 -0.024691  0.034793
50 -0.043657 -0.023311 -0.038415  ... -0.046161  0.952122  0.011766 -0.029817
51 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.011421  0.975309  0.004885
52 -0.043657 -0.023311 -0.038415  ...  0.018449 -0.047878  0.010011  0.970183
53 -0.043657  0.040146 -0.038415  ...  0.047315 -0.047878 -0.024691  0.009628
54 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
55 -0.043657 -0.023311 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
56  0.004675  0.027829 -0.038415  ... -0.046161 -0.047878 -0.024691 -0.029817
57  0.015304 -0.023311 -0.038415  ... -0.046161  0.021150 -0.024691  0.012853
58 -0.043657  0.027496 -0.038415  ... -0.046161 -0.018343 -0.024691 -0.029817

          53        54        55        56        57        58
0  -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
1  -0.034203 -0.038627 -0.019414 -0.024320  0.005359 -0.003937
2  -0.034203 -0.038627 -0.019414 -0.024320  0.041766 -0.010030
3  -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
4  -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
5  -0.034203  0.818398 -0.019414  0.029160 -0.030832 -0.041092
6  -0.034203  0.015605 -0.019414 -0.024320 -0.030832 -0.041092
7  -0.034203 -0.038627 -0.019414  0.024012  0.028128 -0.041092
8   0.029253 -0.038627 -0.019414  0.026820 -0.030832  0.009715
9  -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
10 -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
11  0.008097 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
12  0.031004  0.016038 -0.019414 -0.024320 -0.030832 -0.041092
13 -0.034203 -0.038627 -0.019414  0.011468 -0.030832 -0.041092
14 -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
15 -0.034203 -0.038627  0.033237 -0.024320  0.021513 -0.041092
16 -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
17  0.019935  0.097428 -0.019414 -0.024320  0.002365  0.046095
18  0.059273 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
19 -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
20 -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
21 -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
22  0.019083 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
23  0.021309 -0.038627 -0.019414  0.020417 -0.001257 -0.041092
24 -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
25 -0.034203 -0.038627 -0.019414 -0.024320  0.015724 -0.041092
26  0.029175 -0.038627 -0.019414 -0.024320 -0.002814  0.958908
27 -0.034203 -0.038627 -0.019414 -0.024320  0.013460 -0.041092
28 -0.034203 -0.038627 -0.019414 -0.024320  0.016277 -0.041092
29 -0.034203 -0.038627 -0.019414 -0.024320  0.022822 -0.041092
30 -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
31 -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
32  0.011444 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
33 -0.034203  0.030255 -0.019414 -0.024320 -0.007937  0.019038
34  0.034481 -0.038627  0.073386 -0.024320 -0.030832 -0.041092
35 -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
36  0.053409 -0.038627 -0.019414 -0.024320  0.028010 -0.041092
37 -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
38 -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
39 -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
40 -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
41 -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
42 -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
43 -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
44 -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
45 -0.034203 -0.038627 -0.019414  0.024012  0.028128 -0.041092
46  0.031004  0.016038 -0.019414 -0.024320 -0.030832 -0.041092
47 -0.034203 -0.038627 -0.019414 -0.024320  0.005359 -0.003937
48 -0.034203 -0.038627 -0.019414  0.011468 -0.030832 -0.041092
49  0.059273 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
50 -0.034203 -0.038627 -0.019414 -0.024320  0.038196 -0.011557
51 -0.034203 -0.038627 -0.019414 -0.024320 -0.030832 -0.041092
52  0.005241 -0.038627 -0.019414 -0.024320  0.011838 -0.041092
53  0.965797 -0.038627 -0.019414  0.039473 -0.030832  0.022286
54 -0.034203  0.961373 -0.019414  0.029160 -0.030832 -0.041092
55 -0.034203 -0.038627  0.980586 -0.024320 -0.030832 -0.041092
56  0.029590  0.014853 -0.019414  0.975680 -0.030832 -0.041092
57 -0.034203 -0.038627 -0.019414 -0.024320  0.969168 -0.013074
58  0.029175 -0.038627 -0.019414 -0.024320 -0.002814  0.958908

[59 rows x 59 columns]

,0,1,2,3,4,5,6,7,8,9,...,49,50,51,52,53,54,55,56,57,58
0,1.000000,-0.064935,-0.073250,-0.053282,-0.031174,-0.059559,0.086730,0.066993,-0.037381,-0.056825,...,-0.070541,-0.078937,-0.042957,0.049265,-0.066727,-0.060551,-0.033819,-0.042135,-0.052405,-0.064316
1,-0.064935,1.000000,0.039157,-0.060500,-0.039619,-0.065585,-0.056224,-0.068936,-0.048283,-0.062322,...,-0.076087,0.094206,-0.051341,-0.063591,-0.071676,-0.064751,-0.042279,-0.052933,0.019705,0.013573
2,-0.073250,0.039157,1.000000,-0.066960,-0.049435,-0.074853,-0.061450,-0.077858,-0.057297,-0.070697,...,-0.083482,0.993487,0.019757,-0.071335,-0.075140,-0.074286,-0.052179,-0.062757,0.088171,-0.007759
3,-0.053282,-0.060500,-0.066960,1.000000,-0.025328,-0.056775,-0.042870,-0.065819,-0.036563,-0.052438,...,-0.066513,-0.072738,0.136903,0.029744,-0.061019,-0.057770,-0.027964,-0.040737,-0.053887,-0.059887
4,-0.031174,-0.039619,-0.049435,-0.025328,1.000000,-0.031589,-0.000365,-0.047033,0.008510,-0.028874,...,-0.047237,-0.057365,0.003650,-0.010758,-0.025462,-0.033043,0.020003,0.003270,-0.015613,-0.038830
5,-0.059559,-0.065585,-0.074853,-0.056775,-0.031589,1.000000,0.070945,-0.072599,-0.036918,-0.058308,...,-0.071852,-0.081092,-0.047790,-0.057681,-0.060301,0.984955,-0.034429,0.070404,-0.060748,-0.062227
6,0.086730,-0.056224,-0.061450,-0.042870,-0.000365,0.070945,1.000000,-0.058740,0.210570,-0.046447,...,-0.058380,-0.069637,-0.015383,-0.024592,-0.036130,0.069274,-0.003952,-0.009625,-0.038963,-0.050286
7,0.066993,-0.068936,-0.077858,-0.065819,-0.047033,-0.072599,-0.058740,1.000000,-0.056636,-0.067381,...,-0.083867,-0.071652,-0.062303,-0.067050,-0.079540,-0.073565,-0.049686,0.049296,0.051992,-0.075199
8,-0.037381,-0.048283,-0.057297,-0.036563,0.008510,-0.036918,0.210570,-0.056636,1.000000,-0.040145,...,-0.054440,-0.065426,-0.010131,-0.022386,0.096711,-0.038368,0.004909,0.093001,-0.028354,0.062469
9,-0.056825,-0.062322,-0.070697,-0.052438,-0.028874,-0.058308,-0.046447,-0.067381,-0.040145,1.000000,...,-0.066492,-0.076425,-0.043939,-0.052696,-0.061452,-0.057759,-0.028295,-0.044354,-0.052964,-0.060853
10,-0.050609,-0.055387,-0.063641,-0.046254,-0.020580,-0.050618,-0.038095,-0.062249,-0.031777,-0.047594,...,-0.061055,-0.069403,-0.035518,-0.044529,-0.054531,-0.048901,-0.023211,-0.035907,-0.048481,-0.053275
11,-0.044404,-0.055862,0.027217,-0.042718,-0.005155,-0.046008,0.287775,-0.068651,0.092242,-0.049225,...,0.085082,0.017119,0.043696,0.032712,0.048430,-0.045182,-0.008770,-0.020914,-0.036494,-0.052338
12,-0.065026,-0.070087,-0.076068,-0.060600,-0.039852,0.054053,-0.050240,-0.074898,-0.048237,-0.062311,...,-0.074188,-0.081953,-0.053987,-0.064227,0.071328,0.052818,-0.042506,-0.046658,-0.067484,-0.065936
13,-0.065546,0.022177,0.032790,-0.070503,-0.053317,-0.078026,-0.070971,0.203019,-0.063433,-0.073211,...,-0.088610,0.119095,-0.063920,-0.079815,-0.083310,-0.078984,-0.055978,0.019455,-0.059420,-0.076623
14,-0.035448,-0.043938,-0.053912,-0.029573,0.017958,-0.030123,-0.006059,-0.051359,0.002816,-0.033137,...,-0.053986,-0.061849,-0.002086,-0.016577,-0.022023,-0.031586,0.014366,-0.002484,-0.021477,-0.043142
15,-0.049100,-0.055969,-0.065307,-0.043527,-0.002113,-0.048906,-0.024963,-0.062790,-0.017497,0.030845,...,0.020474,-0.073506,-0.020948,0.064037,-0.034758,-0.047958,0.104019,-0.023009,0.067009,-0.053516
16,-0.046864,-0.055309,-0.063995,-0.037880,0.001618,-0.048456,-0.022104,-0.062597,-0.013412,-0.044569,...,0.321193,-0.071869,0.087692,-0.007896,-0.014018,-0.049861,-0.001936,-0.018774,-0.037690,-0.054510
17,-0.085389,0.012278,-0.014933,-0.079569,-0.050280,0.103441,-0.054210,-0.096603,-0.051871,0.004248,...,0.102001,-0.021639,-0.066080,0.007467,0.047490,0.167240,-0.048332,-0.057803,-0.003121,0.107913
18,-0.070541,-0.076087,-0.083482,-0.066513,-0.047237,-0.071852,-0.058380,-0.083867,-0.054440,-0.066492,...,1.000000,-0.089321,-0.054519,0.072537,0.126097,-0.069172,-0.048817,-0.061099,-0.073917,-0.069876
19,-0.029267,-0.037700,-0.047454,-0.023429,0.026155,-0.029542,0.002214,-0.045118,0.011098,-0.026970,...,-0.047744,-0.055389,0.006252,-0.008132,-0.022828,-0.031000,0.022577,0.005880,-0.012972,-0.036913
20,-0.029278,-0.039597,-0.049418,-0.023903,0.023666,-0.031558,-0.000300,-0.047017,0.008582,-0.028845,...,-0.047087,-0.057354,0.005604,0.098696,-0.023252,-0.033014,0.020082,0.003339,-0.013210,-0.038808
21,-0.037597,-0.044918,-0.051429,-0.030154,0.014958,-0.035645,-0.006466,-0.053493,-0.000181,-0.035287,...,-0.055038,-0.059596,-0.005092,-0.017740,-0.031198,-0.037093,0.011368,-0.005498,-0.023276,-0.042974
22,-0.049594,-0.060970,-0.070063,-0.049666,-0.008718,-0.047963,-0.033037,0.068002,-0.020820,0.025698,...,-0.060665,-0.078288,-0.029270,-0.036299,0.065049,-0.043391,-0.007365,-0.020157,-0.033926,-0.054359
23,-0.051387,-0.056038,0.008393,-0.044234,-0.003186,-0.049372,-0.029981,-0.060015,-0.015336,-0.051077,...,-0.067116,0.002555,0.040784,-0.027951,0.066557,-0.050813,-0.009299,0.068748,0.025301,-0.056719
24,-0.034004,-0.042465,-0.052370,-0.028150,0.019741,-0.034629,-0.004211,-0.049870,0.004648,-0.024911,...,-0.049508,-0.060290,-0.000232,-0.014669,-0.029381,-0.036077,0.016159,-0.000623,-0.016181,-0.041673
25,-0.044155,-0.046204,0.053500,-0.039829,0.008626,-0.041997,-0.015204,-0.059755,-0.011096,-0.043423,...,-0.059946,0.042831,-0.006481,-0.023363,-0.040635,-0.043440,0.000551,-0.012587,0.071691,-0.046096
26,-0.064316,0.013573,-0.007759,-0.059887,-0.038830,-0.062227,-0.050286,-0.075199,0.062469,-0.060853,...,-0.069876,-0.013524,-0.052419,-0.060019,0.068546,-0.059619,-0.041487,-0.049686,0.000856,1.000000
27,-0.036391,-0.042032,-0.049158,-0.030506,0.016763,-0.034571,-0.007286,-0.048228,0.001595,-0.031467,...,-0.051527,-0.057406,-0.003320,-0.013963,-0.022453,-0.032999,0.013165,-0.003722,0.070569,-0.039824
28,0.050043,-0.056652,-0.058687,-0.038162,0.000154,-0.048988,-0.017814,-0.060556,-0.017832,-0.048429,...,-0.060392,-0.067201,0.113375,0.189096,-0.039627,-0.050419,-0.006130,-0.020534,0.065570,-0.054651
29,-0.043406,-0.049564,-0.058440,-0.037499,0.007240,-0.042327,-0.014656,-0.057081,-0.007976,0.151655,...,-0.061071,-0.066556,-0.012939,-0.025258,-0.042324,-0.043766,0.003639,-0.013368,0.075602,-0.048111
30,-0.033508,-0.041963,-0.051848,-0.027657,0.020393,-0.034096,-0.003551,-0.049366,0.005308,-0.027169,...,-0.051988,-0.059768,0.000434,-0.013994,-0.028699,-0.035545,0.016812,0.000045,-0.015502,-0.041171
31,-0.038660,-0.048146,-0.055640,-0.034246,0.011906,-0.039824,-0.010974,-0.056171,-0.003348,-0.035045,...,0.016095,-0.063775,-0.005270,-0.012019,-0.027203,-0.041274,0.012796,-0.008725,-0.023291,-0.046774
32,-0.056839,-0.054961,0.087009,-0.049137,-0.010302,-0.055084,-0.034622,-0.059508,-0.022893,-0.053534,...,-0.071291,0.082582,-0.024601,-0.041949,0.048200,-0.056513,-0.013948,-0.022695,-0.035130,-0.059516
33,-0.069301,-0.007049,-0.026323,-0.066690,-0.032757,0.090446,0.048102,-0.089149,-0.036837,-0.064094,...,-0.023267,-0.033666,-0.047350,-0.051444,-0.054037,0.092784,-0.032554,-0.046856,-0.003961,0.058622
34,-0.049118,-0.055990,-0.066693,-0.043163,-0.000157,-0.047665,-0.023114,-0.063626,-0.011194,0.023176,...,0.014325,-0.074715,-0.020520,-0.023957,0.096920,-0.047005,0.181947,-0.016619,-0.034976,-0.050311
35,-0.051646,-0.057761,-0.068644,-0.045686,-0.003627,-0.048991,-0.026032,-0.065476,-0.018971,0.049354,...,0.039011,-0.076688,-0.024013,-0.026413,-0.033847,-0.047409,0.005338,-0.024477,-0.036181,-0.054485
36,-0.046537,-0.048575,0.044066,-0.042450,0.000811,-0.050073,-0.023378,-0.054332,-0.009036,-0.046062,...,-0.061169,0.038155,-0.012373,-0.022015,0.129582,-0.051504,-0.002813,-0.011701,0.090442,-0.048972
37,-0.031683,-0.040140,-0.049981,-0.025829,0.022966,0.059912,0.002152,-0.047561,0.007872,-0.029380,...,-0.050187,-0.057919,0.003003,-0.011426,-0.026147,0.005771,0.019381,0.005779,-0.016290,-0.039349
38,-0.038891,-0.048725,-0.055382,-0.034281,0.144177,-0.041256,-0.012379,-0.056151,-0.003506,-0.037863,...,0.049042,-0.063509,-0.004737,-0.012245,-0.026498,-0.042699,0.008105,-0.007238,-0.021868,-0.047921
39,-0.038135,-0.046920,-0.055510,0.048483,0.013099,-0.038204,-0.001516,-0.055178,0.000158,-0.036879,...,-0.053136,-0.063587,0.001593,0.046474,-0.033151,-0.039654,0.009491,-0.007481,-0.024394,-0.045312
40,-0.037217,-0.047065,-0.053382,0.067486,0.013984,-0.039479,-0.010113,-0.054500,-0.001227,-0.036210,...,-0.055335,-0.061534,0.003800,0.060705,-0.029334,-0.040927,0.010378,-0.004688,-0.022761,-0.046264
41,1.000000,-0.064935,-0.073250,-0.053282,-0.031174,-0.059559,0.086730,0.066993,-0.037381,-0.056825,...,-0.070541,-0.078937,-0.042957,0.049265,-0.066727,-0.060551,-0.033819,-0.042135,-0.052405,-0.064316
42,-0.056825,-0.062322,-0.070697,-0.052438,-0.028874,-0.058308,-0.046447,-0.067381,-0.040145,1.000000,...,-0.066492,-0.076425,-0.043939,-0.052696,-0.061452,-0.057759,-0.028295,-0.044354,-0.052964,-0.060853
43,-0.053282,-0.060500,-0.066960,1.000000,-0.025328,-0.056775,-0.042870,-0.065819,-0.036563,-0.052438,...,-0.066513,-0.072738,0.136903,0.029744,-0.061019,-0.057770,-0.027964,-0.040737,-0.053887,-0.059887
44,-0.050609,-0.055387,-0.063641,-0.046254,-0.020580,-0.050618,-0.038095,-0.062249,-0.031777,-0.047594,...,-0.061055,-0.069403,-0.035518,-0.044529,-0.054531,-0.048901,-0.023211,-0.035907,-0.048481,-0.053275
45,0.066993,-0.068936,-0.077858,-0.065819,-0.047033,-0.072599,-0.058740,1.000000,-0.056636,-0.067381,...,-0.083867,-0.071652,-0.062303,-0.067050,-0.079540,-0.073565,-0.049686,0.049296,0.051992,-0.075199
46,-0.065026,-0.070087,-0.076068,-0.060600,-0.039852,0.054053,-0.050240,-0.074898,-0.048237,-0.062311,...,-0.074188,-0.081953,-0.053987,-0.064227,0.071328,0.052818,-0.042506,-0.046658,-0.067484,-0.065936
47,-0.064935,1.000000,0.039157,-0.060500,-0.039619,-0.065585,-0.056224,-0.068936,-0.048283,-0.062322,...,-0.076087,0.094206,-0.051341,-0.063591,-0.071676,-0.064751,-0.042279,-0.052933,0.019705,0.013573
48,-0.065546,0.022177,0.032790,-0.070503,-0.053317,-0.078026,-0.070971,0.203019,-0.063433,-0.073211,...,-0.088610,0.119095,-0.063920,-0.079815,-0.083310,-0.078984,-0.055978,0.019455,-0.059420,-0.076623
49,-0.070541,-0.076087,-0.083482,-0.066513,-0.047237,-0.071852,-0.058380,-0.083867,-0.054440,-0.066492,...,1.000000,-0.089321,-0.054519,0.072537,0.126097,-0.069172,-0.048817,-0.061099,-0.073917,-0.069876
50,-0.078937,0.094206,0.993487,-0.072738,-0.057365,-0.081092,-0.069637,-0.071652,-0.065426,-0.076425,...,-0.089321,1.000000,0.009926,-0.079578,-0.083747,-0.080590,-0.060102,-0.066474,0.079162,-0.013524
51,-0.042957,-0.051341,0.019757,0.136903,0.003650,-0.047790,-0.015383,-0.062303,-0.010131,-0.043939,...,-0.054519,0.009926,1.000000,0.051791,-0.041779,-0.049224,0.000030,-0.015754,-0.025541,-0.052419
52,0.049265,-0.063591,-0.071335,0.029744,-0.010758,-0.057681,-0.024592,-0.067050,-0.022386,-0.052696,...,0.072537,-0.079578,0.051791,1.000000,0.033528,-0.056977,-0.011994,-0.029317,0.043709,-0.060019
53,-0.066727,-0.071676,-0.075140,-0.061019,-0.025462,-0.060301,-0.036130,-0.079540,0.096711,-0.061452,...,0.126097,-0.083747,-0.041779,0.033528,1.000000,-0.058639,-0.022813,0.086766,-0.052462,0.068546
54,-0.060551,-0.064751,-0.074286,-0.057770,-0.033043,0.984955,0.069274,-0.073565,-0.038368,-0.057759,...,-0.069172,-0.080590,-0.049224,-0.056977,-0.058639,1.000000,-0.035878,0.068716,-0.060276,-0.059619
55,-0.033819,-0.042279,-0.052179,-0.027964,0.020003,-0.034429,-0.003952,-0.049686,0.004909,-0.028295,...,-0.048817,-0.060102,0.000030,-0.011994,-0.022813,-0.035878,1.000000,-0.000360,-0.016546,-0.041487
56,-0.042135,-0.052933,-0.062757,-0.040737,0.003270,0.070404,-0.009625,0.049296,0.093001,-0.044354,...,-0.061099,-0.066474,-0.015754,-0.029317,0.086766,0.068716,-0.000360,1.000000,-0.029799,-0.049686
57,-0.052405,0.019705,0.088171,-0.053887,-0.015613,-0.060748,-0.038963,0.051992,-0.028354,-0.052964,...,-0.073917,0.079162,-0.025541,0.043709,-0.052462,-0.060276,-0.016546,-0.029799,1.000000,0.000856
58,-0.064316,0.013573,-0.007759,-0.059887,-0.038830,-0.062227,-0.050286,-0.075199,0.062469,-0.060853,...,-0.069876,-0.013524,-0.052419,-0.060019,0.068546,-0.059619,-0.041487,-0.049686,0.000856,1.000000

In [ ]:
def get_movie_recommendation(movie_title, cosine_sim=cosine_sim, movies_df=movies_df):
    # get the index of the movie that matches the title
    idx = movies_df[movies_df['title'].str.contains(movie_title)].index[0]

    # get the cosine similarity scores for the movie at the given index
    sim_scores = list(enumerate(cosine_sim[idx]))

    # sort the movies based on their similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # get the top 10 similar movies
    sim_scores = sim_scores[1:11]
    print(sim_scores)
    
    # return the titles of the recommended movies
    movie_indices = [i[0] for i in sim_scores]
    return movies_df['title'].iloc[movie_indices]

In [ ]:
get_movie_recommendation("12 Angry Men")

[(38, 0.06774421995698893), (0, 0.0), (1, 0.0), (2, 0.0), (3, 0.0), (5, 0.0), (6, 0.0), (7, 0.0), (8, 0.0), (9, 0.0)]

38                                The Silence of Others
0                              The Shawshank Redemption
1                                         The Godfather
2                                The Godfather: Part II
3                                       The Dark Knight
5                                      Schindler's List
6         The Lord of the Rings: The Return of the King
7                                          Pulp Fiction
8     The Lord of the Rings: The Fellowship of the Ring
9                                          Forrest Gump
Name: title, dtype: object

In [ ]:
get_movie_recommendation("The Shawshank Redemption")

41                         The Shawshank Redemption
7                                      Pulp Fiction
45                                     Pulp Fiction
6     The Lord of the Rings: The Return of the King
52                                           Aliens
28                               Back to the Future
1                                     The Godfather
2                            The Godfather: Part II
3                                   The Dark Knight
4                                      12 Angry Men
Name: title, dtype: object

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# load the movie dataset
movies_df = pd.read_csv('movies.csv')

# calculate the Term Frequency-Inverse Document Frequency (TF-IDF) matrix for the movie overview
tfidf = TfidfVectorizer(stop_words='english')
movies_df['overview'] = movies_df['overview'].fillna('')
tfidf_matrix = tfidf.fit_transform(movies_df['overview'])

# calculate the cosine similarity between all movies
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# function to get movie recommendations based on similarity scores
def get_movie_recommendation(movie_title, cosine_sim=cosine_sim, movies_df=movies_df):
    # get the index of the movie that matches the title
    idx = movies_df[movies_df['title'].str.contains(movie_title)].index[0]

    # get the cosine similarity scores for the movie at the given index
    sim_scores = list(enumerate(cosine_sim[idx]))

    # sort the movies based on their similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # get the top 10 similar movies
    sim_scores = sim_scores[1:11]
    
    # return the titles of the recommended movies
    movie_indices = [i[0] for i in sim_scores]
    return movies_df['title'].iloc[movie_indices]

In [ ]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

ratings_df = pd.read_csv('ratings.csv')

In [ ]:
ratings_df.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [ ]:
user_item_matrix = ratings_df.pivot_table(index='userId', columns='movieId', values='rating')

In [ ]:
user_item_matrix

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2.5,NaN,NaN,NaN,NaN,NaN,2.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,2.5,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
609,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
user_item_matrix.fillna(0,inplace=True)
user_item_matrix.head()

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
from scipy.sparse import csr_matrix
csr_data = csr_matrix(user_item_matrix.values)
user_item_matrix.reset_index(inplace=True)

In [ ]:
csr_data

<610x9724 sparse matrix of type '<class 'numpy.float64'>'
	with 100836 stored elements in Compressed Sparse Row format>

In [ ]:
user_item_matrix

movieId,userId,1,2,3,4,5,6,7,8,9,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
0,1,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605,606,2.5,0.0,0.0,0.0,0.0,0.0,2.5,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
606,607,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,608,2.5,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,609,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
609,610,5.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
user_item_matrix.drop('userId',axis=1)

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
0,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605,2.5,0.0,0.0,0.0,0.0,0.0,2.5,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
606,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,2.5,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
609,5.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
from sklearn.neighbors import NearestNeighbors
knn = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=20, n_jobs=-1)
knn.fit(csr_data)

NearestNeighbors(algorithm='brute', metric='cosine', n_jobs=-1, n_neighbors=20)

In [ ]:
user_similarity1 = cosine_similarity(user_item_matrix)

In [ ]:
user_similarity1

array([[1.        , 0.02852282, 0.06124958, ..., 0.05979751, 0.01786371,
        0.04619308],
       [0.02852282, 1.        , 0.01366524, ..., 0.09786919, 0.0926933 ,
        0.11191229],
       [0.06124958, 0.01366524, 1.        , ..., 0.15023547, 0.14871513,
        0.15214023],
       ...,
       [0.05979751, 0.09786919, 0.15023547, ..., 1.        , 0.9879631 ,
        0.97491551],
       [0.01786371, 0.0926933 , 0.14871513, ..., 0.9879631 , 1.        ,
        0.97567154],
       [0.04619308, 0.11191229, 0.15214023, ..., 0.97491551, 0.97567154,
        1.        ]])

In [ ]:
def get_movie_recommendations(user_id, k=5):
    # find the k most similar users
    similar_users = user_similarity1[user_id].argsort()[::-1][1:k+1]
    print(similar_users)
    
    # get movies the user has not watched
    watched_movies = user_item_matrix.loc[user_id]
    print(watched_movies)
    unwatched_movies = watched_movies[watched_movies.isnull()]
    print(unwatched_movies)
    
    # recommend movies based on the ratings of similar users
    recommendations = []
    for movie_title in unwatched_movies.index:
        movie_ratings = user_item_matrix.loc[similar_users, movie_title]
        avg_rating = movie_ratings.mean()
        recommendations.append((movie_title, avg_rating))
        
    # sort the recommendations by average rating
    recommendations = sorted(recommendations, key=lambda x: x[1], reverse=True)
    
    return recommendations

In [ ]:
get_movie_recommendations(609)

[572 560 559 550 581]
movieId
userId    610.0
1           5.0
2           0.0
3           0.0
4           0.0
          ...
193581      0.0
193583      0.0
193585      0.0
193587      0.0
193609      0.0
Name: 609, Length: 9725, dtype: float64
Series([], Name: 609, dtype: float64)

[]

In [ ]:
user_ratings_count = ratings_df.groupby('userId').count()['movieId']

In [ ]:
user_ratings_count

userId
1       232
2        29
3        39
4       216
5        44
       ...
606    1115
607     187
608     831
609      37
610    1302
Name: movieId, Length: 610, dtype: int64

In [ ]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

# load the movie dataset
ratings_df = pd.read_csv('ratings.csv')

# create a user-item matrix
user_item_matrix = ratings_df.pivot_table(index='userId', columns='title', values='rating')

# calculate the similarity between users
user_similarity = cosine_similarity(user_item_matrix)

# function to get movie recommendations for a user
def get_movie_recommendations(user_id, k=10):
    # find the k most similar users
    similar_users = user_similarity[user_id].argsort()[::-1][1:k+1]
    
    # get movies the user has not watched
    watched_movies = user_item_matrix.loc[user_id]
    unwatched_movies = watched_movies[watched_movies.isnull()]
    
    # recommend movies based on the ratings of similar users
    recommendations = []
    for movie_title in unwatched_movies.index:
        movie_ratings = user_item_matrix.loc[similar_users, movie_title]
        avg_rating = movie_ratings.mean()
        recommendations.append((movie_title, avg_rating))
        
    # sort the recommendations by average rating
    recommendations = sorted(recommendations, key=lambda x: x[1], reverse=True)
    
    return recommendations

KeyError: ignored

In [ ]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors

# load the movie dataset
ratings_df = pd.read_csv('ratings.csv')

# create a user-item matrix
user_item_matrix = ratings_df.pivot_table(index='userId', columns='movieId', values='rating')

# fill missing values with 0
user_item_matrix.fillna(0, inplace=True)

# convert user-item matrix to a sparse matrix
csr_data = csr_matrix(user_item_matrix.values)

# fit nearest neighbors model
knn = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=20, n_jobs=-1)
knn.fit(csr_data)

# function to get movie recommendations for a user
def get_movie_recommendations3(user_id, k=10):
    # find the k most similar users
    user_idx = user_item_matrix.index.get_loc(user_id)
    distances, indices = knn.kneighbors(user_item_matrix.iloc[user_idx,:].values.reshape(1,-1),n_neighbors=k+1)
    similarities = 1-distances.flatten()
    
    # get movies the user has not watched
    watched_movies = user_item_matrix.loc[user_id]
    unwatched_movies = watched_movies[watched_movies==0].index
    
    # recommend movies based on the ratings of similar users
    recommendations = []
    for i in range(1,len(indices.flatten())):
        similar_user = user_item_matrix.index[indices.flatten()[i]]
        similar_user_ratings = user_item_matrix.loc[similar_user]
        unwatched_similar_user_ratings = similar_user_ratings[similar_user_ratings.index.isin(unwatched_movies)]
        avg_rating = unwatched_similar_user_ratings.mean()
        recommendations.append((similar_user, avg_rating))
        
    # sort the recommendations by average rating
    recommendations = sorted(recommendations, key=lambda x: x[1], reverse=True)
    
    return recommendations

In [ ]:
get_movie_recommendations3(1)

[(288, 0.2939317319848293),
 (91, 0.1592920353982301),
 (469, 0.13621997471554995),
 (57, 0.12737041719342604),
 (45, 0.11994310998735777),
 (368, 0.10429835651074588),
 (313, 0.08428150021070376),
 (452, 0.061999578592498945),
 (266, 0.03792667509481669),
 (39, 0.020859671302149177)]

In [ ]:
def get_movie_recommendations5(user_id, k=10):
    # find the k most similar users
    user_idx = user_item_matrix.index.get_loc(user_id)
    distances, indices = knn.kneighbors(user_item_matrix.iloc[user_idx,:].values.reshape(1,-1),n_neighbors=k+1)
    similarities = 1-distances.flatten()
    
    # get movies the user has not watched
    watched_movies = user_item_matrix.loc[user_id]
    unwatched_movies = watched_movies[watched_movies==0].index
    
    # recommend movies based on the ratings of similar users
    recommendations = []
    for i in range(1,len(indices.flatten())):
        similar_user = user_item_matrix.index[indices.flatten()[i]]
        similar_user_ratings = user_item_matrix.loc[similar_user]
        unwatched_similar_user_ratings = similar_user_ratings[similar_user_ratings.index.isin(unwatched_movies)]
        avg_rating = unwatched_similar_user_ratings.mean()
        
        # extract the movie IDs from the user-item matrix based on the index positions
        recommended_movies = unwatched_similar_user_ratings.index[unwatched_similar_user_ratings.nonzero()[0]]
        recommendations.append((similar_user, recommended_movies))
        
    # sort the recommendations by average rating
    recommendations = sorted(recommendations, key=lambda x: x[1], reverse=True)
    
    return recommendations

In [ ]:

userRatings = ratings.pivot_table(index=['userId'],columns=['title'],values='rating')
userRatings.head()
print("Before: ",userRatings.shape)
userRatings = userRatings.dropna(thresh=10, axis=1).fillna(0,axis=1)
#userRatings.fillna(0, inplace=True)
print("After: ",userRatings.shape)